#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Environment successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19
    timestamp: 2019-01-02T14:06:58.611-07:00
  environment: 
    id: 9fe156aa-5b63-450c-8e20-ad065dd12d80
    name: Development
    type: sandbox
    runtimeVersions:
      -
        version: "3.9.0"
        applicationsUsing: 3
      -
        version: "3.8.6"
        applicationsUsing: 6
      - 
        version: "3.8.5"
        applicationsUsing: 3
  totalApplications: 12
